#!/usr/bin/env python

import sys, os

def usage():
	sys.stderr.write("Usage: %s [-s|-r]\n" % sys.argv[0])
	sys.exit(1)

if len(sys.argv) < 2:
	usage()

known_args = ["-s", "-r"]
arg = sys.argv[1]

if arg not in known_args:
	usage()

from memo.entities import connect
from memo.tutor import prepare_test
from memo.messaging import send_test, parse_reply

dbname = os.path.join(os.environ['HOME'], ".memo", "db.sqlite")
connect("sqlite:" + dbname)

if arg == "-s":
	send_test(prepare_test(), os.environ['MEMO_ADDRESS'])
elif arg == "-r":
	parse_reply(sys.stdin)
else:
	raise Exception("Unexpected arg: " + arg)
